### ISSUE TITLE
Clean up innocuous Derby-related exception output when running tests

### ISSUE THREAD

**Issue by emetsger** [rmap-project/rmap#167]
Tests that use the Derby embedded database spam the console with exceptions that seem innocuous.  Confirm that the exceptions are benign, and prevent the from appearing.  Example undesired output is below:

* `Caused by: org.apache.derby.iapi.error.StandardException: Directory memory:/Users/esm/workspaces/rmap/rmap/webapp/target/test-classes/derby/inmemoryDatasource cannot be removed.`
* `09:36:10.718 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.`
* `09:36:10.718 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01`
* `09:36:19.595 [Thread-7] WARN  o.s.j.d.e.DerbyEmbeddedDatabaseConfigurer - Could not shut down embedded Derby database
java.sql.SQLException: Database 'memory:inmemoryDatasource' not found.`

```java
esm:~/workspaces/rmap/rmap/webapp (sds-pr-prep)$ git log -n 1 --oneline
813344f Implement embedded-solr for tests
esm:~/workspaces/rmap/rmap/webapp (sds-pr-prep)$ mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building RMap Webapp 1.0.1-beta-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-resource (add-resource) @ rmap-webapp ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ rmap-webapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ rmap-webapp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ rmap-webapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ rmap-webapp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ rmap-webapp ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running info.rmapproject.webapp.controllers.AdminToolControllerTest
09:36:07.069 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
09:36:07.113 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
09:36:10.718 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:10.718 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:10.798 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:10.800 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:10.939 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:10.940 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:10.947 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:10.947 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:10.985 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:10.985 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:11.034 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:11.034 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:11.045 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:11.045 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:11.246 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:11.246 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:11.313 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:11.314 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.394 s - in info.rmapproject.webapp.controllers.AdminToolControllerTest
[INFO] Running info.rmapproject.webapp.controllers.ApiKeyControllerTest
09:36:11.634 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:11.634 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:11.700 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:11.701 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.308 s - in info.rmapproject.webapp.controllers.ApiKeyControllerTest
[INFO] Running info.rmapproject.webapp.controllers.HomeControllerTest
09:36:13.663 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
09:36:13.683 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.386 s - in info.rmapproject.webapp.controllers.HomeControllerTest
[INFO] Running info.rmapproject.webapp.controllers.ResourceDisplayControllerTest
09:36:14.287 [main] ERROR i.r.w.c.ExceptionHandlingController - null
info.rmapproject.core.exception.RMapObjectNotFoundException: null
	at info.rmapproject.webapp.service.DataDisplayServiceImpl.getResourceBatch(DataDisplayServiceImpl.java:386)
	at info.rmapproject.webapp.controllers.ResourceDisplayController.resource(ResourceDisplayController.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:166)
	at info.rmapproject.webapp.controllers.ResourceDisplayControllerTest.testBadResourcePath(ResourceDisplayControllerTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.223 s - in info.rmapproject.webapp.controllers.ResourceDisplayControllerTest
[INFO] Running info.rmapproject.webapp.controllers.SearchControllerTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.215 s - in info.rmapproject.webapp.controllers.SearchControllerTest
[INFO] Running info.rmapproject.webapp.controllers.SitePropertiesToModelInterceptorTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 s - in info.rmapproject.webapp.controllers.SitePropertiesToModelInterceptorTest
[INFO] Running info.rmapproject.webapp.domain.GraphTests
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 s - in info.rmapproject.webapp.domain.GraphTests
[INFO] Running info.rmapproject.webapp.service.DataDisplayServiceImplTest
09:36:16.446 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
09:36:16.464 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.665 s - in info.rmapproject.webapp.service.DataDisplayServiceImplTest
[INFO] Running info.rmapproject.webapp.service.RMapUpdateServiceImplTest
09:36:18.713 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
09:36:18.722 [main] WARN  o.s.data.convert.CustomConversions - Registering converter from interface org.springframework.data.solr.core.query.Update to class org.apache.solr.common.SolrInputDocument as writing converter although it doesn't convert to a store-supported type! You might wanna check you annotation setup at the converter implementation.
09:36:19.318 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:19.318 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:19.334 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:19.334 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
09:36:19.337 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
09:36:19.338 [main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'memory:inmemoryDatasource' not created, connection made to existing database instead.
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.93 s - in info.rmapproject.webapp.service.RMapUpdateServiceImplTest
[INFO] Running info.rmapproject.webapp.service.UserServiceImplTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in info.rmapproject.webapp.service.UserServiceImplTest
[INFO] Running info.rmapproject.webapp.utils.WebappUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 s - in info.rmapproject.webapp.utils.WebappUtilsTest
09:36:19.595 [Thread-7] WARN  o.s.j.d.e.DerbyEmbeddedDatabaseConfigurer - Could not shut down embedded Derby database
java.sql.SQLException: Database 'memory:inmemoryDatasource' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.springframework.jdbc.datasource.embedded.DerbyEmbeddedDatabaseConfigurer.shutdown(DerbyEmbeddedDatabaseConfigurer.java:74)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory.shutdownDatabase(EmbeddedDatabaseFactory.java:228)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactoryBean.destroy(EmbeddedDatabaseFactoryBean.java:90)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
Caused by: org.apache.derby.iapi.error.StandardException: Database 'memory:inmemoryDatasource' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 27 common frames omitted
09:36:19.601 [Thread-3] WARN  o.s.j.d.e.DerbyEmbeddedDatabaseConfigurer - Could not shut down embedded Derby database
java.sql.SQLException: Database 'memory:inmemoryDatasource' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.springframework.jdbc.datasource.embedded.DerbyEmbeddedDatabaseConfigurer.shutdown(DerbyEmbeddedDatabaseConfigurer.java:74)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory.shutdownDatabase(EmbeddedDatabaseFactory.java:228)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactoryBean.destroy(EmbeddedDatabaseFactoryBean.java:90)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
Caused by: org.apache.derby.iapi.error.StandardException: Database 'memory:inmemoryDatasource' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 27 common frames omitted
09:36:20.202 [Thread-9] WARN  o.s.j.d.e.DerbyEmbeddedDatabaseConfigurer - Could not shut down embedded Derby database
java.sql.SQLException: Directory memory:/Users/esm/workspaces/rmap/rmap/webapp/target/test-classes/derby/inmemoryDatasource cannot be removed.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.springframework.jdbc.datasource.embedded.DerbyEmbeddedDatabaseConfigurer.shutdown(DerbyEmbeddedDatabaseConfigurer.java:74)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory.shutdownDatabase(EmbeddedDatabaseFactory.java:228)
	at org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactoryBean.destroy(EmbeddedDatabaseFactoryBean.java:90)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:953)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:960)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933)
Caused by: org.apache.derby.iapi.error.StandardException: Directory memory:/Users/esm/workspaces/rmap/rmap/webapp/target/test-classes/derby/inmemoryDatasource cannot be removed.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.removePersistentService(Unknown Source)
	at org.apache.derby.impl.services.monitor.FileMonitor.removePersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.removePersistentService(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.jdbc.EmbedConnection.removePersistentService(Unknown Source)
	... 21 common frames omitted
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 33, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.905 s
[INFO] Finished at: 2017-12-20T09:36:20-05:00
[INFO] Final Memory: 29M/437M
[INFO] ------------------------------------------------------------------------
esm:~/workspaces/rmap/rmap/webapp (sds-pr-prep)$ 
```

**Comment by emetsger** [comment]
Obsolete with #210 (switch from Derby to Postgres) applied.
