### ISSUE TITLE
Insure triplestore transaction state is properly maintained

### ISSUE THREAD

**Issue by emetsger** [rmap-project/rmap#175]
There is a suspected interplay between the indexing code and event manager code, where the indexer is somehow corrupting the triplestore transaction state when a DiSCO is attempted to be created.

This situation can be re-created by attempting to rapidly create discos.

The stacktrace that results is:
```
[WARNING] [talledLocalContainer] 11:19:32.295 [2-thread-1] WARN  [  SparqlSession] - Server reports problem: transaction with id 1955021f-4f3d-4d24-ad0a-f07641e49d4e is no longer registered!
[WARNING] [talledLocalContainer] 11:19:33.403 [2-thread-1] WARN  [HTTPRepositoryC] - Rolling back transaction due to connection close
[INFO] [talledLocalContainer] java.lang.Throwable: null
[INFO] [talledLocalContainer]   at org.openrdf.repository.http.HTTPRepositoryConnection.close(HTTPRepositoryConnection.java:384)
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.triplestore.SesameTriplestore.closeConnection(SesameTriplestore.java:119)
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapService.closeConnection(ORMapService.java:146)
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapService.readDiSCO(ORMapService.java:353)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.getDisco(DefaultIndexRetryHandler.java:240)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.composeDTO(DefaultIndexRetryHandler.java:231)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.retry(DefaultIndexRetryHandler.java:183)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.IndexingConsumer.indexEvent(IndexingConsumer.java:154)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.IndexingConsumer.lambda$consume$0(IndexingConsumer.java:119)
[INFO] [talledLocalContainer]   at java.lang.Iterable.forEach(Iterable.java:75)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.IndexingConsumer.consume(IndexingConsumer.java:102)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.SpringAwareConsumerInitializer.lambda$startConsumers$4(SpringAwareConsumerInitializer.java:204)
[INFO] [talledLocalContainer]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] [talledLocalContainer]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [talledLocalContainer]   at java.lang.Thread.run(Thread.java:745)
[WARNING] [talledLocalContainer] 11:19:33.488 [63-exec-10] ERROR [RMapApiExceptio] - A system error occurred in the RMap Service; RMapException: Exception thrown committing new triples to triplestore
[INFO] [talledLocalContainer] info.rmapproject.api.exception.RMapApiException: Exception thrown committing new triples to triplestore
[INFO] [talledLocalContainer]   at info.rmapproject.api.exception.RMapApiException.wrap(RMapApiException.java:52)
[INFO] [talledLocalContainer]   at info.rmapproject.api.responsemgr.DiscoResponseManager.createRMapDiSCO(DiscoResponseManager.java:482)
[INFO] [talledLocalContainer]   at info.rmapproject.api.service.DiSCOApiService.apiCreateRMapDiSCO(DiSCOApiService.java:242)
[INFO] [talledLocalContainer]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] [talledLocalContainer]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] [talledLocalContainer]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] [talledLocalContainer]   at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] [talledLocalContainer]   at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
[INFO] [talledLocalContainer]   at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
[INFO] [talledLocalContainer]   at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
[INFO] [talledLocalContainer]   at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
[INFO] [talledLocalContainer]   at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
[INFO] [talledLocalContainer]   at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
[INFO] [talledLocalContainer]   at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
[INFO] [talledLocalContainer]   at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
[INFO] [talledLocalContainer]   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[INFO] [talledLocalContainer]   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
[INFO] [talledLocalContainer]   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
[INFO] [talledLocalContainer]   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
[INFO] [talledLocalContainer]   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
[INFO] [talledLocalContainer]   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
[INFO] [talledLocalContainer]   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
[INFO] [talledLocalContainer]   at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
[INFO] [talledLocalContainer]   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [talledLocalContainer]   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[INFO] [talledLocalContainer]   at java.lang.Thread.run(Thread.java:745)
[INFO] [talledLocalContainer] Caused by: info.rmapproject.core.exception.RMapException: Exception thrown committing new triples to triplestore
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapDiSCOMgr.createDiSCO(ORMapDiSCOMgr.java:236)
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapService.createDiSCO(ORMapService.java:373)
[INFO] [talledLocalContainer]   at info.rmapproject.api.responsemgr.DiscoResponseManager.createRMapDiSCO(DiscoResponseManager.java:443)
[INFO] [talledLocalContainer]   ... 43 common frames omitted
[WARNING] [talledLocalContainer] 11:20:48.920 [2-thread-1] WARN  [IndexingConsume] - Unable to index event ORMapObject{id=rmap:dpxatro9s0, typeStatement=(rmap:dpxatro9s0, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://purl.org/ontology/rmap#Event) [rmap:dpxatro9s0], context=rmap:dpxatro9s0}: Timeout after 10 attempts, 75073 ms: failed to index ORMapObject{id=rmap:dpxatro9s0, typeStatement=(rmap:dpxatro9s0, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://purl.org/ontology/rmap#Event) [rmap:dpxatro9s0], context=rmap:dpxatro9s0}: No DiSCO with id rmap:l5hbjvtagg
[INFO] [talledLocalContainer] info.rmapproject.indexing.IndexingTimeoutException: Timeout after 10 attempts, 75073 ms: failed to index ORMapObject{id=rmap:dpxatro9s0, typeStatement=(rmap:dpxatro9s0, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://purl.org/ontology/rmap#Event) [rmap:dpxatro9s0], context=rmap:dpxatro9s0}: No DiSCO with id rmap:l5hbjvtagg
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.retry(DefaultIndexRetryHandler.java:224)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.IndexingConsumer.indexEvent(IndexingConsumer.java:154)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.IndexingConsumer.lambda$consume$0(IndexingConsumer.java:119)
[INFO] [talledLocalContainer]   at java.lang.Iterable.forEach(Iterable.java:75)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.IndexingConsumer.consume(IndexingConsumer.java:102)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.SpringAwareConsumerInitializer.lambda$startConsumers$4(SpringAwareConsumerInitializer.java:204)
[INFO] [talledLocalContainer]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] [talledLocalContainer]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [talledLocalContainer]   at java.lang.Thread.run(Thread.java:745)
[INFO] [talledLocalContainer] Caused by: info.rmapproject.core.exception.RMapDiSCONotFoundException: No DiSCO with id rmap:l5hbjvtagg
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapDiSCOMgr.readDiSCO(ORMapDiSCOMgr.java:140)
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapDiSCOMgr.readDiSCO(ORMapDiSCOMgr.java:114)
[INFO] [talledLocalContainer]   at info.rmapproject.core.rmapservice.impl.openrdf.ORMapService.readDiSCO(ORMapService.java:350)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.getDisco(DefaultIndexRetryHandler.java:240)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.composeDTO(DefaultIndexRetryHandler.java:231)
[INFO] [talledLocalContainer]   at info.rmapproject.indexing.kafka.DefaultIndexRetryHandler.retry(DefaultIndexRetryHandler.java:183)
[INFO] [talledLocalContainer]   ... 10 common frames omitted
```

**Comment by emetsger** [comment]
This seems to be resolved by changing the `ORMapService` class to  `prototype` scope, implemented in 075b902.

An instance of `ORMapService` is not meant to be shared by multiple threads.  Adding `prototype` scope, in this case, seems to fix the issue.  Leaving this open for a few days just in case we discover this fix isn't enough.

**Comment by emetsger** [comment]
@karenhanson I think this issue can be closed, what do you think?

**Comment by karenhanson** [comment]
agree - closing!
