### ISSUE TITLE
post-integration-test phase order leads to database connection errors

### ISSUE THREAD

**Issue by emetsger** [rmap-project/rmap#213]
After the ITs execute in `rmap-integration`, currently an exception can be thrown when the Docker container for Postgres shuts down before the JDBC DataSource is closed by Spring (during Cargo shutdown).  The exception emitted at the end of the IT execution is benign (it doesn't fail the build), but it is noisy.

Hopefully re-ordering the plugins that execute during the `post-integration-test` phase should allow for the correct shutdown order, and prevent the exception from occurring.

#### pre-integration-test
- start docker
- start cargo

#### integration-test
- failsafe

#### post-integration-test
- stop cargo (JDBC DataSources closed)
- stop docker (Postgres container shuts down)

```java
[INFO] [talledLocalContainer] Jan 30, 2018 4:27:37 AM org.postgresql.core.v3.ConnectionFactoryImpl log
[WARNING] [talledLocalContainer] WARNING: ConnectException occurred while connecting to localhost:43445
[INFO] [talledLocalContainer] java.net.ConnectException: Connection refused (Connection refused)
[INFO] [talledLocalContainer] 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[INFO] [talledLocalContainer] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[INFO] [talledLocalContainer] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[INFO] [talledLocalContainer] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[INFO] [talledLocalContainer] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[INFO] [talledLocalContainer] 	at java.net.Socket.connect(Socket.java:589)
[INFO] [talledLocalContainer] 	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
[INFO] [talledLocalContainer] 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:158)
[INFO] [talledLocalContainer] 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[INFO] [talledLocalContainer] 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
[INFO] [talledLocalContainer] 	at org.postgresql.Driver.makeConnection(Driver.java:452)
[INFO] [talledLocalContainer] 	at org.postgresql.Driver.connect(Driver.java:254)
[INFO] [talledLocalContainer] 	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
[INFO] [talledLocalContainer] 	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
[INFO] [talledLocalContainer] 	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
[INFO] [talledLocalContainer] 	at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
[INFO] [talledLocalContainer] 	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
[INFO] [talledLocalContainer] 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
[INFO] [talledLocalContainer] 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
[INFO] [talledLocalContainer] 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
[INFO] [talledLocalContainer] 	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:46)
[INFO] [talledLocalContainer] 	at org.springframework.jdbc.datasource.init.DataSourceInitializer.execute(DataSourceInitializer.java:111)
[INFO] [talledLocalContainer] 	at org.springframework.jdbc.datasource.init.DataSourceInitializer.destroy(DataSourceInitializer.java:105)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:576)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:552)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:955)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:521)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:227)
[INFO] [talledLocalContainer] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:962)
[INFO] [talledLocalContainer] 	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1037)
[INFO] [talledLocalContainer] 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1013)
[INFO] [talledLocalContainer] 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:963)
[INFO] [talledLocalContainer] 	at org.springframework.web.servlet.FrameworkServlet.destroy(FrameworkServlet.java:838)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1432)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1768)
[INFO] [talledLocalContainer] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5524)
[INFO] [talledLocalContainer] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424)
[INFO] [talledLocalContainer] 	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1413)
[INFO] [talledLocalContainer] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] [talledLocalContainer] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by emetsger** [comment]
Actually this is an error with jdbc database population, and it seems to be related to attempting to execute a destroy/teardown method (i.e. something trying to remove database rows or tables, or the database itself).
