### ISSUE TITLE
Error when retrieving a disco via api or webapp after loading to dev server

### ISSUE THREAD

**Issue by karenhanson** [rmap-project/rmap#81]
Integration test spring profiles work for creation and retrieval of DiSCO through the API or webapp. When war files were installed on the dev server, however, the following error occurred when trying to load a DiSCO through either the API or the webapp: 

```20:47:19.769 [http-nio-8081-exec-5] ERROR info.rmapproject.webapp.controllers.ExceptionHandlingController - Invalid profile []: must contain text
java.lang.IllegalArgumentException: Invalid profile []: must contain text
        at org.springframework.core.env.AbstractEnvironment.validateProfile(AbstractEnvironment.java:354)
        at org.springframework.core.env.AbstractEnvironment.addActiveProfile(AbstractEnvironment.java:264)
        at info.rmapproject.core.model.impl.openrdf.ORMapObject.lambda$new$0(ORMapObject.java:74)
        at info.rmapproject.core.model.impl.openrdf.ORMapObject$$Lambda$23/1510403249.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at info.rmapproject.core.model.impl.openrdf.ORMapObject.<init>(ORMapObject.java:74)
        at info.rmapproject.core.model.impl.openrdf.ORMapDiSCO.<init>(ORMapDiSCO.java:122)
        at info.rmapproject.core.rmapservice.impl.openrdf.ORMapDiSCOMgr.readDiSCO(ORMapDiSCOMgr.java:141)
        at info.rmapproject.core.rmapservice.impl.openrdf.ORMapService.readDiSCO(ORMapService.java:309)
        at info.rmapproject.webapp.service.DataDisplayServiceImpl.getDiSCODTO(DataDisplayServiceImpl.java:145)
        at info.rmapproject.webapp.controllers.DiSCODataController.disco(DiSCODataController.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)```

**Comment by emetsger** [comment]
The `web.xml` for each web application needs to [define a context parameter](https://github.com/rmap-project/rmap/blob/master/webapp/src/main/webapp/WEB-INF/web.xml#L10-L13) named `spring.profiles.default` with a comma-separated list of the spring profiles to activate, in this case: `default,persistent-db,http-idservice,http-triplestore,persistent-userservice`.

After adding that context parameter to each web application, they should start up without issue!

**Comment by karenhanson** [comment]
The web.xml context-param for spring.profiles.default is identical to the one in github.  It's reading the property as empty. I confirmed this by adding a few log lines.

**Comment by emetsger** [comment]
Ah!  Ok, the issue is [here](https://github.com/rmap-project/rmap/blob/master/core/src/main/java/info/rmapproject/core/model/impl/openrdf/ORMapObject.java#L72-L73) in `ORMapObject`:

The system property `spring.profiles.default` also needs to be set, unfortunately (to the same value: `default,persistent-db,http-idservice,http-triplestore,persistent-userservice`).  So that would need to be set up in Tomcat's `setenv.sh` or where ever your container's environment is configured.

**Comment by karenhanson** [comment]
This was resolved by setting the spring.profiles.default property, will be documented during wiki updates
